### ISSUE TITLE
Support for Java 11+

### ISSUE THREAD

**Issue by pwittchen** [py4j/py4j#403]
Hi,

It seems that py4j is not working properly with Java 11. I have no issues with Java 8. Do you have plans to support Java versions higher than 8? Inside build configuration, I cannot see details related to Java higher than 8.

Regards,
Piotr

**Comment by pwittchen** [comment]
Can you give any comments on this?

**Comment by deb75** [comment]
It works for me with java 11, cannot set for 12, 13, ...

What kind of bugs did youy experience ?

**Comment by johann-petrak** [comment]
I would also be very interested in the exact details about which Java versions can be used and where problems are to be expected. 

If there are know issues with "recent" Java versions, especially LTS versions, I think this should get mentioned prominently in the README and on the main documentation page.

**Comment by bartdag** [comment]
A detailed error report with stack trace, error message, version of Java, Python, and OS would help tremendously. 

Java 11 is not included in the test suite, but I could try to add it once Travis-ci.org moves to to Travis-ci.com.

There were some changes to the security model of reflection in Java 9 so some code that used to work well in Java 8 may require additional flags (e.g., --illegal-access=warn). There were also some changes regarding the default class loader so complex applications or environments (looking at you OSGi) may require some modifications but without complete error reports, it is not possible for me to know if Py4J or the user code must be changed.

**Comment by johann-petrak** [comment]
(Just using github actions for unit testing or linting instead of Travis.com may be the easier and faster way forward, at least that was my experience after struggling with travis for some time)

**Comment by Thrameos** [comment]
If it is any help JPype switched from travis to azure a while back.  We have pretty good patterns to build and test many architectures including 8 and 11.  See ``.azure``  in the JPype tree.  We also have building modules for many architeture release down.  But given I don't see a C portion this likely isnt needed here.

As for Java 9+, the module system was added which controls access to reflection by adding a new security model.  The solution may be as easy as adding a module-info.java to the base of the source tree and modifying the build pattern to enable modules.  Unfortunately I dont have this one down as JPype uses C JNI reflection and thus may have different access rules. 

From what i have gathered in studying this issue, generally there is nothing that changes in the new security model other than having the meaning of public change.  Before implementation details are public classes due to lack of the concept of friend.  After this those modules are now marked as module private even though they still have a public flag.  For a bridge code this means that when constucting the reflection list the module permisions need to be tested first to decide if the tree should stop at a public base class.  For the user they would just see the class come back as the last open class.  Messing with the accessablity flags on a class that isnt open to you is likely to triggle problems.  Also pulling up module aware though the class loader is likely to trigger this, though i am less sure on this.  Though in Jpype honestly as most of the reflection is done in Java I am surprised that I dont hit the same issue.

If there were a user example of how to trigger this issue I may be able to solve it here as well as trying to triggle the same in JPype.  I know a fair amount about the reflection process and class loaders.  If this is just a minor hurtle to get over the transition I may be able to help.   Is py4j playing with the accessablity flags perhaps?

**Comment by bartdag** [comment]
@Thrameos thanks a lot for your input. I really really appreciate this!

Py4J definitively touches the accessibility flag.

For fields, we only check if the field is Public and accessible before accessing them (if they are not public and accessible, we don't allow direct reading):

```java
if (!Modifier.isPublic(field.getModifiers()) && !field.isAccessible())
```

For methods and constructors we always set the accessible flag to True before calling them. This allows users to call protected, package or private methods:

```java
			if (method != null) {
				AccessController.doPrivileged(new PrivilegedAction<Object>() {
					public Object run() {
						method.setAccessible(true);
						return null;
					}
				});
				returnObject = method.invoke(obj, newArguments);
			} else if (constructor != null) {
				constructor.setAccessible(true);
				returnObject = constructor.newInstance(newArguments);
			}
```

My understanding is that for public methods, this will be fine, but for protected, package, and private methods, Java 9 will complain.

I don't think we natively call these methods in Py4J code. We probably have some unit tests calling private methods to test that particular piece of code though.

**Comment by Thrameos** [comment]
Lets go over options for transiting between Java 8 and Java 9+.

State of Java
-----------------------------------
First lets look as the awkward state of Java currently.   Prior to Java 9 the security model of Java was basically the wild west.  There was a security controller which looked as the caller and did different behaviors depending on which package it came from for system level calls, but otherwise using reflection and ``setAccessible`` you could drill down to some vulnerable native call and then exploit it.  It made any  prospect of secure operations of Java impossible if you don't control the source of the jars you are loading. (which really isn't different from running untrusted shared libraries).

So starting in Java 9 they added the new security model.  But because this will break code they wanted to give a transition period because at the same time they decided to change their payment model.  This created almost the same problem as Python 2 to Python 3.   The end of live date for Java 8 ranges from 2030 to 2026 depending on the vender.  Thus for library developers such as us, we are going to have to deal with the fact that we will need to support both the new and old for a very long time.   Apparently Java learned their lessons from Python 2 and decided long and painful was the best option.

They did give us new tools to deal with the transition.  It is difficult (but not impossible) to write code that works on both the old and the new model.  You can use reflection to look for the new methods and then call them instead.  That is currently what JPype does.   Alternatively you can supply two different implementations of a class.  The old one is located in the usual location and the new one with the alternative implementation is placed in a second location.   You then build a "multi-release" jar file in which the jar file loader will look at the version and determine the appropriate implementation.

You can find an example of this in JPype under ``project/jars/mrjar``.  Basically every time that we run into these new tools it breaks some portion of the reflection process.  So to make sure that we deal with it properly I have cooked up patterns to create different flavors of jar files (missing directory entries, missing dependencies, and multi-release jars).  It should help you to see how they get built and give you a start on finding the documentation to build a version which supports both Java 8 and Java 9+.

The procedure for your library is simple.   
1) Update the source code by updating the ``setAccessible`` with the corresponding replacement.
2) Test the replacement to make sure the behavior is acceptable.
3) Copy the replacement to a separate tree and restore the old one so Java 8 will work.
4) Change the build to compile the new one in as a multi-release jar so that Java 9+ will work.
5) Victory!  You now have a version that works for both Java 8 and Java 9+.

Dealing with setAccessible
------------------------------
So now that we have down what we can do to transition lets get into the options of fixing it.

Currently when you run the code you will get a scary warning.  This warning is intended to tell you that the default for ``--illegal-access`` will be changing from ``permit`` to ``deny`` in the "future" version.  But it has been saying that since Java 9 and we are at Java 15+ at this point, so clearly the future has not arrived.  The good news is we can see the effect just by starting Java with ``--illegal-access=deny`` option.

Currently we get.

```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.example.Test (file:/home/nelson85/j9test/classes/) to method java.lang.String.rangeCheck(char[],int,int)
WARNING: Please consider reporting this to the maintainers of org.example.Test
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```

The future behavior will be.

```
Exception in thread "main" java.lang.reflect.InaccessibleObjectException: Unable to make private static java.lang.Void java.lang.String.rangeCheck(char[],int,int) accessible: module java.base does not "opens java.lang" to unnamed module @4dc63996
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:340)
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:280)
        at java.base/java.lang.reflect.Method.checkCanSetAccessible(Method.java:198)
        at java.base/java.lang.reflect.Method.setAccessible(Method.java:192)
        at org.example.Test.main(Test.java:18)
```

If we convert the jar to a module then we get the future behavior regardless of the option setting.

Thus your options.
1) Remove all use of setAccessible and label the previous behavior as a misfeature.  Quite frankly the setting of methods that are not public is dangerous. If this breaks a users code then likely they were doing something they were not supposed to do.  

2) Convert your code to a module and then use ``--add-opens`` to the arguments for Java.   You can pierce the security system if you choose.  The intent of the system was to prevent an untrusted module from accessing code to exploit, but you can add exceptions to make your code trusted.  The downside is that you can  only open one module at a time.  There doesn't appear to be a blanket open all to this package. But this is sufficient if you just need access to testing the private parts of some code.  And a user can open a module for testing as well, you just need to give a list of modules you wish to open to the start gateway and everything will work as before.  This will require old code that wants to use this to set that option so it may be undesirable.

Further reading:
https://stackoverflow.com/questions/44056405/whats-the-difference-between-add-exports-and-add-opens-in-java-9
https://docs.oracle.com/javase/9/migrate/toc.htm#JSMIG-GUID-7744EF96-5899-4FB2-B34E-86D49B2E89B6

You can use add-opens even without converting to a module, but this has the downside that you will be openning
up modules to all jars not just yours.

3) Use ``trySetAccessible`` instead.  The old call will throw on a problem.  So they gave a method which just attempts the access.  If the access fails it returns false and you can tell the user that the operation was not permitted.  Unfortunately as Java 8 doesn't have this option, you end up with the requirement for a multi-release jar.  You will need to add a list of "module_open" to the gateway starting option so that the user can select modules they want private access to.

I would recommend option 1 as the safest.   You just need to filter the list of methods that you get from ``getDeclaredMethods`` based on ``isAccessible`` and only expose the ones that the user should have access to just like fields.   If the user wants to do something dangerous, they can use reflection through the gateway to get ahold of the method in question, use the add-opens option when starting the gateway to make ``setAccessible`` possible, and then call the ``setAccessible`` themselves.  This leave your code as safe by default but allows the user to do bad things if they really want.  

The next best alternative is 3.    That would make is so that most of the time you have public access only, but when the add-open is called the private and protected methods appear.   Given mostly compatible with the current behavior.

Hope this helps.  I have patterns for things like how to convert to a module and such.   Unfortunately I am not an eclipse user so all my solutions are for plain old command line building which is what I use for distribution as I don't want to require any tools except Python and JDK for compiling.

**Comment by torokati44** [comment]
Starting with Java 17, the `--illegal-access=permit` VM argument no longer works.
I tried the 3. option outlined above (using `trySetAccessible()` instead of `setAccessible(true)` in `MethodInvoker`), and it mostly works.
Except for the specific case of returning a `HashMap` from Java to Python.
That still runs into an invalid access exception when doing `self.keySet().iterator()` in `java_collections.py`.

The weird thing is, that with this simple example application: https://gist.github.com/torokati44/642da15a9523a272c4d7c9ea20cc3bb7
The direct invocation of `hashMap.keySet().iterator()` works just fine, as expected, but the same thing done through reflection fails.

I tried to instead invoke the "highest super-method" of `iterator()` (inherited from `Collection` I believe) - https://gist.github.com/torokati44/27b3147e54bc1aee8ed77e8911c1c277 -, and that way it works.
In the example snippet, that is... But not in an Eclipse product for some reason...

Why is it, that an ordinary chained method call is fine when I do it directly, but not allowed through reflection?

**Comment by torokati44** [comment]
Related: https://bugs.java.com/bugdatabase/view_bug.do?bug_id=4071957

**Comment by torokati44** [comment]
The reason it didn't work "in Eclipse" was not even specific to Eclipse at all.

It's just that in that scenario, the iteration (`hasNext()` and `next()` on the returned iterator) was also done from Python, so through reflection in Java.

And those methods, in `HashMap.HashIterator` are only public via `java.lang.Iterator`. And that is an interface, not a superclass (starts with an `I`, after all, right?! hahh...), so simply walking through the superclass chain is not sufficient to get a usable `Method` - the implemented interfaces should also be included.

That way, it works also in the Eclipse product! I shall prepare a PR with these changes in the coming days.

**Comment by HyukjinKwon** [comment]
Hey guys, we plan to work on it in this quarter. I will leave it closed this as a duplicate of https://github.com/py4j/py4j/issues/485. Let's track it there.
