### ISSUE TITLE
JDK 11 and 17 support

### ISSUE THREAD

**Issue by HyukjinKwon** [py4j/py4j#485]
See
- https://github.com/py4j/py4j/pull/453
- https://github.com/py4j/py4j/issues/403
- https://github.com/py4j/py4j/issues/448

We should:
- Set up the CI for JDK 11/17
- See how we'd like to release. e.g.) compile with JDK 8 to make one release working with both 11/17 (like Apache Spark does as an example).

**Comment by johann-petrak** [comment]
A lot of important and useful comments are in issues #453 and especially #403 which hopefully do not get ignored because these issues have been closed! 

From my side I think one important issue is that we **need** to know which Java versions are known to work / not work or are officially supported and which are not, or maybe also which things may not work for certain Java versions,  and prominently show that information in the main README file and on the documentation site.

**Comment by johann-petrak** [comment]
Also is there any active development branch for work on this issue or does master reflect the most recent status?

**Comment by HyukjinKwon** [comment]
This is WIP. ETA is around end of next month. The draft will be shared when it's ready soon.
