### ISSUE TITLE
?) "*.equals(" code inside py.

### ISSUE THREAD

**Issue by MvGulik** [py4j/py4j#539]
Total Java noob here, that's more at home with Python.

I'm wondering about the "```*.equals(``` code part inside the [java_gateway.py](https://github.com/py4j/py4j/blob/f4e3f1009008333bf44baf7fb7573291a955c955/py4j-python/src/py4j/java_gateway.py#L1452) file.
(_I know about pythons ```__eq__``` part._)

Is that correct code ?
Considering ".equals" is a general Java thing and not a python thing.
(_did not look for a potential python definition on this though_)

Its only seems to be used 2 times in py4j pythons files. (second one is in some test py file ... so its a rare case)

What is the target here ?
As I have run into something similar inside some code that uses py4j. But which triggers a py error.
But I can't figuring out what its intended to do  ... so I can potential fix it.

**Comment by HyukjinKwon** [comment]
It's for JVM object comparison. Was there any issue by that?

**Comment by MvGulik** [comment]
I don't know. I don't understand that last code line. so can't tel what the real problem is (_or potentially fix it ... correctly_).

Related pyj4 local code.
Which btw it not part of the original py4j source code ... but somewhat similar to what I found in the [java_gateway.py](https://github.com/py4j/py4j/blob/f4e3f1009008333bf44baf7fb7573291a955c955/py4j-python/src/py4j/java_gateway.py#L1452) file.
```
class PBotItem(object):
    def __init__(self, item):
        self.__item = item
        self._item = item

    def __eq__(self, other):
        if other is None:
            return False
        return self.__item.equals(other._item)
```

Which triggers this error when ```def __eq__(...)``` is indirectly called by my DEBUG call.
```
    DEBUG('.. '+'item_at_hand', item_at_hand)
  File "/.../_Python_/_Includes_/DEBUG.py", line 194, in DEBUG
    if data == 'fOObAr': ## no data-part input.
  File "/.../__pbot/PBotItem.py", line 12, in __eq__
    return self.__item.equals(other._item)
AttributeError: 'str' object has no attribute '_item'
```
I'm totally mystified about the  ```.equals(``` part (+its part of some larger bulk code using py4j). Which makes debugging this kinda hard (at least for me).

(+_Original coder of the bulk code is also no longer available._)

**Comment by MvGulik** [comment]
> It's for JVM object comparison.
Yea. but is that not just a Java thing. While this is inside some python code.

**Comment by jdayton3** [comment]
@MvGulik in the java_gateway.py code you linked:

```python
def __eq__(self, other):
    if other is None:
        return False
    elif (hasattr2(other, "_get_object_id")):
        return self.equals(other)
    else:
        return other.__eq__(self)
```

We only use `self.equals()` if `other` has `_get_object_id` defined. Since `_get_object_id` is a method defined on `JavaObject`, I take this to be a "duck typing" way to determine whether `other` can also be treated like a `JavaObject`, in which case we can delegate equality to Java. If `other` can't be treated like a `JavaObject`, we default to `other`'s method of determining equality.

As far as the question (my words, not yours):

> Where does `self.equals()` get defined, since it's not explicitly defined as a method on the class & we're not inheriting from any other class that defines `.equals()`?

Check the [`__getattr__` definition](https://github.com/py4j/py4j/blob/f4e3f1009008333bf44baf7fb7573291a955c955/py4j-python/src/py4j/java_gateway.py#L1386). Since `getattr(x, "name")()` is equivalent to `x.name()`, and defining `__getattr__` is how we define the behavior of `getattr` for a class, `self.equals()` is calling the Java `.equals()` implementation by way of `self.__getattr__(name="equals")` -> `self._get_field(name="equals")`.

In your `PBotItem` constructor, it looks like there are 2 implicit assumptions:

1. `item` is of type `JavaObject` (or otherwise has `.equals()` defined)
2. `other` is of type `PBotItem` (or otherwise has `._item` defined)

Given your error message, it looks like you're trying to check whether equality between a `PBotItem` and a `str`, which is not necessarily an issue with py4j.

```python
In [1]: class FakeJavaObject:
   ...:     def equals(self, other):
   ...:         return True
   ...:

In [2]: class PBotItem(object):
   ...:     def __init__(self, item):
   ...:         self.__item = item
   ...:         self._item = item
   ...:
   ...:     def __eq__(self, other):
   ...:         if other is None:
   ...:             return False
   ...:         return self.__item.equals(other._item)
   ...:

In [3]: x = PBotItem(FakeJavaObject())

In [4]: x == "y"
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[4], line 1
----> 1 x == "y"

Cell In[2], line 9, in PBotItem.__eq__(self, other)
      7 if other is None:
      8     return False
----> 9 return self.__item.equals(other._item)

AttributeError: 'str' object has no attribute '_item'
```

**Comment by MvGulik** [comment]
@jdayton3
Thanks for the extensive info/help.

After digesting your message for the first time. Things already start to make more sens.
(_extracting whatever else I can from it will take some additional time and studying_)

So basically ... If I got it right. The problem in the related PBotItem code is that the ```__eq__(self. other)``` part (_if other is not None_) blindly defaults to calling the Java equals part (_ie: letting Java do the comparing. I need to so some additional reading-up on that part_) ... without checking if that "other" thing is actually a valid parameter/type/thing in this case.

I think I now should be able to fix this problem ... one way or an other.
Thank you.

Closing (_As resolved/explained, +The error source was not part of py4j's own code._)
